// AUTO-GENERATED from FUND_STRATEGY___ONBOARDING_QUESTIONNAIRE_-_Copy.docx
// Data-driven onboarding schema. Add/edit/reorder questions by editing this file only —
// no component changes needed. The wizard, autosave, and asset prompts all read from here.

export type FieldType = "text" | "email" | "tel" | "textarea" | "multi_select";

export interface OnboardingField {
  id: string;
  label: string;
  type: FieldType;
  required: boolean;
  options?: string[];
  placeholder?: string;
}

export interface OnboardingSection {
  id: string;
  title: string;
  description?: string;
  fields: OnboardingField[];
}

export const ONBOARDING_SECTIONS: OnboardingSection[] = [
  {
    id: "general_information",
    title: `General Information`,
    fields: [
      {
        id: "company_name",
        label: `Company Name`,
        type: "text",
        required: false,
      },
      {
        id: "full_name",
        label: `Full Name`,
        type: "text",
        required: false,
      },
      {
        id: "current_title_role",
        label: `Current Title & Role`,
        type: "text",
        required: false,
      },
      {
        id: "investment_vehicle",
        label: `Investment Vehicle`,
        type: "text",
        required: false,
      },
      {
        id: "email",
        label: `Email`,
        type: "email",
        required: false,
      },
      {
        id: "phone_number",
        label: `Phone Number`,
        type: "tel",
        required: false,
      },
      {
        id: "website",
        label: `Website`,
        type: "text",
        required: false,
      },
      {
        id: "linkedin_profile",
        label: `LinkedIn Profile`,
        type: "text",
        required: false,
      },
      {
        id: "preferred_communication_method",
        label: `Preferred Communication Method`,
        type: "text",
        required: false,
      },
      {
        id: "preferred_communication_frequency",
        label: `Preferred Communication Frequency`,
        type: "text",
        required: false,
      },
    ],
  },
  {
    id: "fund_overview_strategy",
    title: `Fund Overview & Strategy`,
    fields: [
      {
        id: "summary_of_fund_strategy",
        label: `Summary of Fund Strategy`,
        type: "textarea",
        required: false,
      },
      {
        id: "how_would_you_describe_your_investment_philosophy",
        label: `How would you describe your investment philosophy?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_is_the_fund_mandate",
        label: `What is the Fund mandate?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_problem_or_market_inefficiency_does_the_fund_aim_to_sol",
        label: `What problem or market inefficiency does the Fund aim to solve?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_are_the_primary_goals_of_the_fund",
        label: `What are the primary goals of the Fund?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_is_the_long_term_vision_of_the_fund",
        label: `What is the long-term vision of the Fund?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_are_the_top_key_differentiators_of_your_fund",
        label: `What are the top key differentiators of your Fund?`,
        type: "textarea",
        required: false,
      },
      {
        id: "are_there_other_similar_funds_in_the_market_if_so_list_3_of_",
        label: `Are there other similar Funds in the market? If so, list 3 of them.`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_benchmarks_should_be_used_to_measure_your_funds_perform",
        label: `What benchmarks should be used to measure your Fund’s performance against competitors?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_proprietary_ip_systems_frameworks_or_advantages_exist_w",
        label: `What proprietary IP, systems, frameworks, or advantages exist within the Fund?`,
        type: "textarea",
        required: false,
      },
      {
        id: "can_you_describe_any_patents_ip_or_proprietary_methodologies",
        label: `Can you describe any patents, IP, or proprietary methodologies owned by the Fund?`,
        type: "textarea",
        required: false,
      },
      {
        id: "is_your_fund_dependent_upon_any_third_parties_to_generate_re",
        label: `Is your Fund dependent upon any third parties to generate results? If so, who?`,
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "market_investment_focus",
    title: `Market & Investment Focus`,
    fields: [
      {
        id: "what_asset_classes_will_the_fund_focus_on",
        label: `What asset classes will the Fund focus on?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_geographies_will_the_fund_focus_on",
        label: `What geographies will the Fund focus on?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_sectors_will_the_fund_focus_on",
        label: `What sectors will the Fund focus on?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_stage_companiesassets_will_the_fund_target",
        label: `What stage companies/assets will the Fund target?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_types_of_investments_will_the_fund_pursue",
        label: `What types of investments will the Fund pursue?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_investment_criteria_are_used_when_evaluating_opportunit",
        label: `What investment criteria are used when evaluating opportunities?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_is_the_average_target_investment_size",
        label: `What is the average target investment size?`,
        type: "textarea",
        required: false,
      },
      {
        id: "how_will_capital_be_deployed",
        label: `How will capital be deployed?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_risk_management_strategies_are_used_within_the_fund",
        label: `What risk management strategies are used within the Fund?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_market_research_exists_related_to_your_strategy_or_targ",
        label: `What market research exists related to your strategy or target market?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_industry_trends_most_influence_your_investment_decision",
        label: `What industry trends most influence your investment decisions?`,
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "investor_profile_market_positioning",
    title: `Investor Profile & Market Positioning`,
    fields: [
      {
        id: "what_type_of_investors_are_you_trying_to_target",
        label: `What type of investors are you trying to target?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_investor_profiles_are_the_strongest_fit_for_your_fund",
        label: `What investor profiles are the strongest fit for your Fund?`,
        type: "textarea",
        required: false,
      },
      {
        id: "are_there_investor_profiles_that_may_not_align_well_with_you",
        label: `Are there investor profiles that may not align well with your strategy?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_investor_profiles_convert_the_fastest",
        label: `What investor profiles convert the fastest?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_motivates_investors_to_allocate_capital_to_your_fund",
        label: `What motivates investors to allocate capital to your Fund?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_emotional_outcomes_are_investors_seeking",
        label: `What emotional outcomes are investors seeking?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_pain_points_does_your_fund_solve_for_investors",
        label: `What pain points does your Fund solve for investors?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_concerns_or_questions_do_prospective_investors_most_com",
        label: `What concerns or questions do prospective investors most commonly raise?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_concerns_typically_delay_investor_decisions",
        label: `What concerns typically delay investor decisions?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_objections_arise_most_frequently_during_investor_conver",
        label: `What objections arise most frequently during investor conversations?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_qualities_or_characteristics_tend_to_build_investor_con",
        label: `What qualities or characteristics tend to build investor confidence most effectively?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_alternatives_are_prospective_investors_currently_consid",
        label: `What alternatives are prospective investors currently considering?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_communication_style_resonates_best_with_your_target_inv",
        label: `What communication style resonates best with your target investors?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_messaging_resonates_most_strongly_with_prospective_inve",
        label: `What messaging resonates most strongly with prospective investors?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_channels_best_reach_your_target_investors",
        label: `What channels best reach your target investors?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_causes_investors_to_take_meetings",
        label: `What causes investors to take meetings?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_causes_investors_to_lose_interest",
        label: `What causes investors to lose interest?`,
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "leadership_communication",
    title: `Leadership & Communication`,
    fields: [
      {
        id: "how_would_you_describe_the_foundermanaging_partners_personal",
        label: `How would you describe the Founder/Managing Partner’s personality?`,
        type: "textarea",
        required: false,
      },
      {
        id: "how_would_you_describe_the_communication_style_of_the_leader",
        label: `How would you describe the communication style of the leadership team?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_core_values_define_the_fund_and_its_leadership",
        label: `What core values define the Fund and its leadership?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_experiences_or_background_most_strongly_influence_the_f",
        label: `What experiences or background most strongly influence the Fund’s philosophy?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_qualities_make_the_leadership_team_uniquely_positioned_",
        label: `What qualities make the leadership team uniquely positioned to execute this strategy?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_viewpoints_or_beliefs_does_the_fund_strongly_agree_or_d",
        label: `What viewpoints or beliefs does the Fund strongly agree or disagree with?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_topics_is_leadership_most_passionate_about",
        label: `What topics is leadership most passionate about?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_public_image_should_the_fund_maintain",
        label: `What public image should the Fund maintain?`,
        type: "textarea",
        required: false,
      },
      {
        id: "how_formal_or_conversational_should_communications_feel",
        label: `How formal or conversational should communications feel?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_messaging_styles_should_be_avoided",
        label: `What messaging styles should be avoided?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_tone_best_represents_the_fund",
        label: `What tone best represents the Fund?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_words_or_phrases_should_never_be_used",
        label: `What words or phrases should never be used?`,
        type: "textarea",
        required: false,
      },
      {
        id: "are_there_public_interviews_podcasts_webinars_articles_or_so",
        label: `Are there public interviews, podcasts, webinars, articles, or social profiles that best represent the leadership team?`,
        type: "textarea",
        required: false,
      },
      {
        id: "are_there_existing_writing_samples_or_communications_that_be",
        label: `Are there existing writing samples or communications that best represent the Founder/Managing Partner voice?`,
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "brand_positioning_communications",
    title: `Brand Positioning & Communications`,
    fields: [
      {
        id: "how_would_you_like_the_fund_to_be_perceived_within_the_marke",
        label: `How would you like the Fund to be perceived within the market?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_emotions_should_the_brand_evoke",
        label: `What emotions should the brand evoke?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_messaging_should_always_be_emphasized",
        label: `What messaging should always be emphasized?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_messaging_should_never_be_used",
        label: `What messaging should never be used?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_themes_or_narratives_should_consistently_be_emphasized",
        label: `What themes or narratives should consistently be emphasized?`,
        type: "textarea",
        required: false,
      },
      {
        id: "are_there_themes_messaging_styles_or_language_that_should_be",
        label: `Are there themes, messaging styles, or language that should be avoided?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_industry_narratives_does_the_fund_strongly_believe_in",
        label: `What industry narratives does the Fund strongly believe in?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_industry_narratives_does_the_fund_disagree_with",
        label: `What industry narratives does the Fund disagree with?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_differentiators_should_consistently_be_highlighted",
        label: `What differentiators should consistently be highlighted?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_brands_firms_or_organizations_best_represent_the_style_",
        label: `What brands, firms, or organizations best represent the style or positioning you admire?`,
        type: "textarea",
        required: false,
      },
      {
        id: "are_there_competitor_brands_or_messaging_approaches_you_disl",
        label: `Are there competitor brands or messaging approaches you dislike or wish to avoid?`,
        type: "textarea",
        required: false,
      },
      {
        id: "how_institutional_versus_conversational_should_communication",
        label: `How institutional versus conversational should communications feel?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_communication_style_should_all_materials_maintain",
        label: `What communication style should all materials maintain?`,
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "fund_structure_operations",
    title: `Fund Structure & Operations`,
    fields: [
      {
        id: "what_is_the_target_fund_size",
        label: `What is the target Fund size?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_is_the_minimum_investment_amount_required_from_investor",
        label: `What is the minimum investment amount required from investors?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_entity_structure_is_preferred",
        label: `What entity structure is preferred?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_state_would_you_like_the_fund_domiciled_in",
        label: `What state would you like the Fund domiciled in?`,
        type: "textarea",
        required: false,
      },
      {
        id: "is_the_fund_evergreen_or_term_based_if_term_based_what_is_th",
        label: `Is the Fund evergreen or term-based? If term-based, what is the duration?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_are_the_anticipated_lock_up_periods",
        label: `What are the anticipated lock-up periods?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_are_the_funds_redemption_allowances_and_restrictions",
        label: `What are the Fund’s redemption allowances and restrictions?`,
        type: "textarea",
        required: false,
      },
      {
        id: "how_frequently_will_investors_be_allowed_to_withdraw_funds",
        label: `How frequently will investors be allowed to withdraw funds?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_fee_structure_is_desired_for_the_fund",
        label: `What fee structure is desired for the Fund?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_are_the_target_fund_returns",
        label: `What are the target Fund returns?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_are_the_expected_operational_costs",
        label: `What are the expected operational costs?`,
        type: "textarea",
        required: false,
      },
      {
        id: "will_leverage_be_used_if_so_what_ratios",
        label: `Will leverage be used? If so, what ratios?`,
        type: "textarea",
        required: false,
      },
      {
        id: "will_the_fund_allow_co_investments",
        label: `Will the Fund allow co-investments?`,
        type: "textarea",
        required: false,
      },
      {
        id: "will_the_fund_require_registration_with_regulatory_bodies",
        label: `Will the Fund require registration with regulatory bodies?`,
        type: "textarea",
        required: false,
      },
      {
        id: "does_the_fund_require_any_compliance_frameworks",
        label: `Does the Fund require any compliance frameworks?`,
        type: "textarea",
        required: false,
      },
      {
        id: "who_will_be_responsible_for_fund_governance",
        label: `Who will be responsible for Fund governance?`,
        type: "textarea",
        required: false,
      },
      {
        id: "will_the_fund_have_an_advisory_board",
        label: `Will the Fund have an Advisory Board?`,
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "service_providers_infrastructure",
    title: `Service Providers & Infrastructure`,
    fields: [
      {
        id: "has_a_fund_administrator_been_identified",
        label: `Has a Fund Administrator been identified?`,
        type: "textarea",
        required: false,
      },
      {
        id: "has_a_fund_auditor_been_identified",
        label: `Has a Fund Auditor been identified?`,
        type: "textarea",
        required: false,
      },
      {
        id: "do_you_have_an_insurance_broker",
        label: `Do you have an Insurance Broker?`,
        type: "textarea",
        required: false,
      },
      {
        id: "does_the_fund_use_a_crm_or_pipeline_management_system",
        label: `Does the Fund use a CRM or pipeline management system?`,
        type: "textarea",
        required: false,
      },
      {
        id: "does_the_fund_already_have_an_existing_investor_network",
        label: `Does the Fund already have an existing investor network?`,
        type: "textarea",
        required: false,
      },
      {
        id: "have_any_fund_entities_already_been_established",
        label: `Have any Fund entities already been established?`,
        type: "textarea",
        required: false,
      },
      {
        id: "has_any_business_already_been_conducted_through_fund_entitie",
        label: `Has any business already been conducted through Fund entities?`,
        type: "textarea",
        required: false,
      },
      {
        id: "entity_names",
        label: `Entity Names`,
        type: "text",
        required: false,
      },
      {
        id: "eins",
        label: `EINs`,
        type: "text",
        required: false,
      },
      {
        id: "sos_filings",
        label: `SOS Filings`,
        type: "text",
        required: false,
      },
      {
        id: "ownership_structures",
        label: `Ownership Structures`,
        type: "text",
        required: false,
      },
      {
        id: "what_operational_toolsplatforms_are_currently_used",
        label: `What operational tools/platforms are currently used?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_systems_are_currently_used_for_investor_reporting",
        label: `What systems are currently used for investor reporting?`,
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "capitalization_governance_structure",
    title: `Capitalization & Governance Structure`,
    fields: [
      {
        id: "management_company_who_is_on_the_cap_table_for_the_managemen",
        label: `Management Company — Who is on the cap table for the Management Company? Please include names and ownership percentages.`,
        type: "textarea",
        required: false,
      },
      {
        id: "management_company_who_are_the_managers_of_the_management_co",
        label: `Management Company — Who are the Managers of the Management Company?`,
        type: "textarea",
        required: false,
      },
      {
        id: "general_partner_who_is_on_the_cap_table_for_the_general_part",
        label: `General Partner — Who is on the cap table for the General Partner? Please include names and ownership percentages.`,
        type: "textarea",
        required: false,
      },
      {
        id: "general_partner_who_are_the_managers_of_the_general_partner",
        label: `General Partner — Who are the Managers of the General Partner?`,
        type: "textarea",
        required: false,
      },
      {
        id: "upper_general_partner_who_is_on_the_cap_table_for_the_upper_",
        label: `Upper General Partner — Who is on the cap table for the Upper General Partner? Please include names and ownership percentages.`,
        type: "textarea",
        required: false,
      },
      {
        id: "upper_general_partner_who_are_the_managers_of_the_upper_gene",
        label: `Upper General Partner — Who are the Managers of the Upper General Partner?`,
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "fundraising_investor_communications",
    title: `Fundraising & Investor Communications`,
    fields: [
      {
        id: "what_questions_do_prospective_investors_most_frequently_ask_",
        label: `What questions do prospective investors most frequently ask during conversations?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_concerns_or_objections_most_commonly_arise_during_fundr",
        label: `What concerns or objections most commonly arise during fundraising discussions?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_has_historically_helped_build_investor_trust_most_effec",
        label: `What has historically helped build investor trust most effectively?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_factors_have_historically_slowed_or_complicated_fundrai",
        label: `What factors have historically slowed or complicated fundraising conversations?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_follow_up_style_has_historically_worked_best",
        label: `What follow-up style has historically worked best?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_communication_channels_have_been_most_effective_for_eng",
        label: `What communication channels have been most effective for engaging prospective investors?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_fundraising_approaches_have_historically_worked_best",
        label: `What fundraising approaches have historically worked best?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_fundraising_approaches_or_messaging_have_historically_u",
        label: `What fundraising approaches or messaging have historically underperformed?`,
        type: "textarea",
        required: false,
      },
      {
        id: "are_there_existing_investor_materials_presentations_or_repor",
        label: `Are there existing investor materials, presentations, or reports available for reference?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_type_of_investor_reporting_will_be_provided",
        label: `What type of investor reporting will be provided?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_reporting_frequency_will_be_provided",
        label: `What reporting frequency will be provided?`,
        type: "textarea",
        required: false,
      },
      {
        id: "do_you_have_any_case_studies_related_to_your_investment_stra",
        label: `Do you have any case studies related to your investment strategy?`,
        type: "textarea",
        required: false,
      },
      {
        id: "have_you_performed_a_qoe_on_prior_related_investment_perform",
        label: `Have you performed a QoE on prior related investment performance?`,
        type: "textarea",
        required: false,
      },
      {
        id: "are_you_expecting_to_raise_capital_outside_of_the_us",
        label: `Are you expecting to raise capital outside of the US?`,
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "public_presence_thought_leadership",
    title: `Public Presence & Thought Leadership`,
    fields: [
      {
        id: "what_topics_should_the_fund_regularly_speak_about_publicly",
        label: `What topics should the Fund regularly speak about publicly?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_topics_would_you_prefer_not_to_publicly_focus_on",
        label: `What topics would you prefer not to publicly focus on?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_educational_themes_should_content_focus_on",
        label: `What educational themes should content focus on?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_type_of_thought_leadership_should_the_fund_establish",
        label: `What type of thought leadership should the Fund establish?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_subjects_position_the_fund_as_a_category_expert",
        label: `What subjects position the Fund as a category expert?`,
        type: "textarea",
        required: false,
      },
      {
        id: "are_there_existing_webinars_podcasts_or_speaking_engagements",
        label: `Are there existing webinars, podcasts, or speaking engagements available?`,
        type: "textarea",
        required: false,
      },
      {
        id: "are_there_existing_recordings_transcripts_or_interviews_avai",
        label: `Are there existing recordings, transcripts, or interviews available?`,
        type: "textarea",
        required: false,
      },
      {
        id: "are_there_preferred_podcast_or_interview_formats",
        label: `Are there preferred podcast or interview formats?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_media_outlets_or_publications_are_priorities",
        label: `What media outlets or publications are priorities?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_speaking_opportunities_are_priorities",
        label: `What speaking opportunities are priorities?`,
        type: "textarea",
        required: false,
      },
      {
        id: "are_there_preferred_influencers_creators_or_media_personalit",
        label: `Are there preferred influencers, creators, or media personalities aligned with the brand?`,
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "visual_branding_creative_direction",
    title: `Visual Branding & Creative Direction`,
    fields: [
      {
        id: "does_the_fund_already_have_brand_identity_guidelines",
        label: `Does the Fund already have brand identity guidelines?`,
        type: "textarea",
        required: false,
      },
      {
        id: "are_there_existing_logos_design_systems_or_visual_assets_ava",
        label: `Are there existing logos, design systems, or visual assets available?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_marketing_materials_currently_exist",
        label: `What marketing materials currently exist?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_marketing_materials_are_needed",
        label: `What marketing materials are needed?`,
        type: "textarea",
        required: false,
      },
      {
        id: "how_would_you_describe_the_desired_visual_identity_of_the_fu",
        label: `How would you describe the desired visual identity of the Fund?`,
        type: "textarea",
        required: false,
      },
      {
        id: "are_there_visual_styles_brands_or_firms_that_best_represent_",
        label: `Are there visual styles, brands, or firms that best represent the desired aesthetic?`,
        type: "textarea",
        required: false,
      },
      {
        id: "are_there_visual_styles_or_approaches_that_should_be_avoided",
        label: `Are there visual styles or approaches that should be avoided?`,
        type: "textarea",
        required: false,
      },
      {
        id: "what_overall_impression_should_the_visual_identity_communica",
        label: `What overall impression should the visual identity communicate?`,
        type: "textarea",
        required: false,
      },
      {
        id: "preferred_visual_style",
        label: `Preferred visual style`,
        type: "multi_select",
        required: false,
        options: ["Luxury", "Institutional", "Modern", "Minimalist", "High-tech", "Traditional", "Editorial", "Aggressive", "Founder-led"],
      },
      {
        id: "preferred_color_palettes",
        label: `Preferred color palettes?`,
        type: "textarea",
        required: false,
      },
      {
        id: "preferred_typography_style",
        label: `Preferred typography style?`,
        type: "textarea",
        required: false,
      },
      {
        id: "visuals_feel",
        label: `Should visuals feel`,
        type: "multi_select",
        required: false,
        options: ["Corporate", "Cinematic", "Documentary-style", "Editorial", "Luxury", "Startup-oriented", "Institutional"],
      },
    ],
  },
  {
    id: "financial_modeling_assumptions",
    title: `Financial Modeling Assumptions`,
    fields: [
      {
        id: "capital_formation_what_is_the_target_raise_amount",
        label: `Capital Formation — What is the target raise amount?`,
        type: "textarea",
        required: false,
      },
      {
        id: "capital_formation_what_is_the_minimum_viable_raise_amount",
        label: `Capital Formation — What is the minimum viable raise amount?`,
        type: "textarea",
        required: false,
      },
      {
        id: "capital_formation_what_is_the_maximum_target_fund_size",
        label: `Capital Formation — What is the maximum target Fund size?`,
        type: "textarea",
        required: false,
      },
      {
        id: "capital_formation_what_is_the_anticipated_fundraising_timeli",
        label: `Capital Formation — What is the anticipated fundraising timeline?`,
        type: "textarea",
        required: false,
      },
      {
        id: "capital_formation_what_capital_call_structure_is_anticipated",
        label: `Capital Formation — What capital call structure is anticipated?`,
        type: "textarea",
        required: false,
      },
      {
        id: "capital_formation_what_percentage_of_capital_is_expected_to_",
        label: `Capital Formation — What percentage of capital is expected to be deployed annually?`,
        type: "textarea",
        required: false,
      },
      {
        id: "deployment_assumptions_what_is_the_expected_average_investme",
        label: `Deployment Assumptions — What is the expected average investment size?`,
        type: "textarea",
        required: false,
      },
      {
        id: "deployment_assumptions_how_many_investments_are_expected_per",
        label: `Deployment Assumptions — How many investments are expected per year?`,
        type: "textarea",
        required: false,
      },
      {
        id: "deployment_assumptions_what_is_the_expected_hold_period_per_",
        label: `Deployment Assumptions — What is the expected hold period per investment?`,
        type: "textarea",
        required: false,
      },
      {
        id: "deployment_assumptions_what_percentage_of_capital_is_expecte",
        label: `Deployment Assumptions — What percentage of capital is expected to remain reserved?`,
        type: "textarea",
        required: false,
      },
      {
        id: "deployment_assumptions_what_percentage_is_expected_to_be_fol",
        label: `Deployment Assumptions — What percentage is expected to be follow-on capital?`,
        type: "textarea",
        required: false,
      },
      {
        id: "deployment_assumptions_what_deployment_pacing_assumptions_sh",
        label: `Deployment Assumptions — What deployment pacing assumptions should be used?`,
        type: "textarea",
        required: false,
      },
      {
        id: "return_assumptions_what_target_irr_is_being_modeled",
        label: `Return Assumptions — What target IRR is being modeled?`,
        type: "textarea",
        required: false,
      },
      {
        id: "return_assumptions_what_target_moic_is_being_modeled",
        label: `Return Assumptions — What target MOIC is being modeled?`,
        type: "textarea",
        required: false,
      },
      {
        id: "return_assumptions_what_expected_loss_ratios_should_be_assum",
        label: `Return Assumptions — What expected loss ratios should be assumed?`,
        type: "textarea",
        required: false,
      },
      {
        id: "return_assumptions_what_upsidedownside_scenarios_should_be_c",
        label: `Return Assumptions — What upside/downside scenarios should be considered?`,
        type: "textarea",
        required: false,
      },
      {
        id: "return_assumptions_what_liquidity_assumptions_should_be_used",
        label: `Return Assumptions — What liquidity assumptions should be used?`,
        type: "textarea",
        required: false,
      },
      {
        id: "revenue_fee_structure_what_management_fee_structure_should_b",
        label: `Revenue & Fee Structure — What management fee structure should be modeled?`,
        type: "textarea",
        required: false,
      },
      {
        id: "revenue_fee_structure_what_carried_interest_structure_should",
        label: `Revenue & Fee Structure — What carried interest structure should be modeled?`,
        type: "textarea",
        required: false,
      },
      {
        id: "revenue_fee_structure_are_there_hurdle_rates",
        label: `Revenue & Fee Structure — Are there hurdle rates?`,
        type: "textarea",
        required: false,
      },
      {
        id: "revenue_fee_structure_are_there_preferred_returns",
        label: `Revenue & Fee Structure — Are there preferred returns?`,
        type: "textarea",
        required: false,
      },
      {
        id: "revenue_fee_structure_are_there_additional_revenue_streams_a",
        label: `Revenue & Fee Structure — Are there additional revenue streams associated with the Fund?`,
        type: "textarea",
        required: false,
      },
      {
        id: "revenue_fee_structure_are_there_servicing_or_operational_fee",
        label: `Revenue & Fee Structure — Are there servicing or operational fees that should be modeled?`,
        type: "textarea",
        required: false,
      },
      {
        id: "operating_expenses_what_annual_operating_costs_should_be_ass",
        label: `Operating Expenses — What annual operating costs should be assumed?`,
        type: "textarea",
        required: false,
      },
      {
        id: "operating_expenses_what_headcount_costs_should_be_modeled",
        label: `Operating Expenses — What headcount costs should be modeled?`,
        type: "textarea",
        required: false,
      },
      {
        id: "operating_expenses_what_technologysoftware_costs_should_be_m",
        label: `Operating Expenses — What technology/software costs should be modeled?`,
        type: "textarea",
        required: false,
      },
      {
        id: "operating_expenses_what_legalcompliance_costs_should_be_mode",
        label: `Operating Expenses — What legal/compliance costs should be modeled?`,
        type: "textarea",
        required: false,
      },
      {
        id: "operating_expenses_what_marketingfundraising_costs_should_be",
        label: `Operating Expenses — What marketing/fundraising costs should be modeled?`,
        type: "textarea",
        required: false,
      },
      {
        id: "operating_expenses_what_travelevent_costs_should_be_modeled",
        label: `Operating Expenses — What travel/event costs should be modeled?`,
        type: "textarea",
        required: false,
      },
      {
        id: "operating_expenses_what_third_party_vendorsservice_providers",
        label: `Operating Expenses — What third-party vendors/service providers should be included?`,
        type: "textarea",
        required: false,
      },
      {
        id: "investor_structure_what_investor_concentration_assumptions_s",
        label: `Investor Structure — What investor concentration assumptions should be modeled?`,
        type: "textarea",
        required: false,
      },
      {
        id: "investor_structure_what_average_investor_check_size_should_b",
        label: `Investor Structure — What average investor check size should be assumed?`,
        type: "textarea",
        required: false,
      },
      {
        id: "investor_structure_what_lp_onboarding_assumptions_should_be_",
        label: `Investor Structure — What LP onboarding assumptions should be used?`,
        type: "textarea",
        required: false,
      },
      {
        id: "investor_structure_what_redemption_assumptions_should_be_mod",
        label: `Investor Structure — What redemption assumptions should be modeled?`,
        type: "textarea",
        required: false,
      },
      {
        id: "investor_structure_what_lock_up_assumptions_should_be_reflec",
        label: `Investor Structure — What lock-up assumptions should be reflected?`,
        type: "textarea",
        required: false,
      },
      {
        id: "scenario_modeling_what_are_the_key_risks_that_may_impact_per",
        label: `Scenario Modeling — What are the key risks that may impact performance?`,
        type: "textarea",
        required: false,
      },
      {
        id: "scenario_modeling_what_downside_scenarios_should_be_consider",
        label: `Scenario Modeling — What downside scenarios should be considered?`,
        type: "textarea",
        required: false,
      },
      {
        id: "scenario_modeling_what_optimistic_growth_assumptions_should_",
        label: `Scenario Modeling — What optimistic growth assumptions should be considered?`,
        type: "textarea",
        required: false,
      },
      {
        id: "scenario_modeling_what_macroeconomic_risks_should_be_modeled",
        label: `Scenario Modeling — What macroeconomic risks should be modeled?`,
        type: "textarea",
        required: false,
      },
      {
        id: "scenario_modeling_what_market_assumptions_are_critical_to_th",
        label: `Scenario Modeling — What market assumptions are critical to the strategy?`,
        type: "textarea",
        required: false,
      },
    ],
  },
  {
    id: "communication_content_workflow_preferences",
    title: `Communication, Content & Workflow Preferences`,
    fields: [
      {
        id: "materials_communications_are_there_existing_webinar_recordin",
        label: `Materials & Communications — Are there existing webinar recordings available?`,
        type: "textarea",
        required: false,
      },
      {
        id: "materials_communications_are_there_existing_podcast_appearan",
        label: `Materials & Communications — Are there existing podcast appearances available?`,
        type: "textarea",
        required: false,
      },
      {
        id: "materials_communications_are_there_existing_investor_present",
        label: `Materials & Communications — Are there existing investor presentations available?`,
        type: "textarea",
        required: false,
      },
      {
        id: "materials_communications_are_there_existing_sales_calls_avai",
        label: `Materials & Communications — Are there existing sales calls available for training purposes?`,
        type: "textarea",
        required: false,
      },
      {
        id: "materials_communications_are_transcripts_available",
        label: `Materials & Communications — Are transcripts available?`,
        type: "textarea",
        required: false,
      },
      {
        id: "materials_communications_are_recordings_available_for_future",
        label: `Materials & Communications — Are recordings available for future media or communication initiatives?`,
        type: "textarea",
        required: false,
      },
      {
        id: "materials_communications_are_there_preferred_clips_or_moment",
        label: `Materials & Communications — Are there preferred clips or moments that best represent the brand?`,
        type: "textarea",
        required: false,
      },
      {
        id: "materials_communications_are_there_internal_knowledge_bases_",
        label: `Materials & Communications — Are there internal knowledge bases or documents available for reference?`,
        type: "textarea",
        required: false,
      },
      {
        id: "communication_workflow_preferences_who_should_review_and_app",
        label: `Communication & Workflow Preferences — Who should review and approve externally-facing materials?`,
        type: "textarea",
        required: false,
      },
      {
        id: "communication_workflow_preferences_are_there_compliance_cons",
        label: `Communication & Workflow Preferences — Are there compliance considerations or communication restrictions we should be aware of?`,
        type: "textarea",
        required: false,
      },
      {
        id: "communication_workflow_preferences_are_there_topics_that_sho",
        label: `Communication & Workflow Preferences — Are there topics that should not be discussed publicly?`,
        type: "textarea",
        required: false,
      },
      {
        id: "comms_feel_more",
        label: `Should communications feel more`,
        type: "multi_select",
        required: false,
        options: ["Institutional", "Conversational", "Founder-led", "Technical", "Academic", "Sales-oriented"],
      },
      {
        id: "communication_workflow_preferences_what_types_of_materials_o",
        label: `Communication & Workflow Preferences — What types of materials or communications should be prioritized during the engagement?`,
        type: "textarea",
        required: false,
      },
    ],
  },
];

export const TOTAL_SECTIONS = ONBOARDING_SECTIONS.length;

export function getSectionById(id: string) {
  return ONBOARDING_SECTIONS.find((s) => s.id === id);
}